BASICS


In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

1.15.2


In [ ]:
hello = tf.constant("Hello")
world = tf.constant("World")

In [ ]:
sess = tf.Session()

In [ ]:
print(sess.run(hello+world))

b'HelloWorld'


In [ ]:
with tf.Session() as sess:
  result = sess.run(hello+world)

In [ ]:
print(result)

b'HelloWorld'


In [ ]:
a = tf.constant(10)
b = tf.constant(20)
sum = a+b

In [ ]:
type(sum)

tensorflow.python.framework.ops.Tensor

In [ ]:
print(sum)

Tensor("add_2:0", shape=(), dtype=int32)


In [ ]:
sess = tf.InteractiveSession()
result = sess.run(sum)

In [ ]:
result

30

In [ ]:
myrand1 = tf.random_normal((4,4),mean=0,stddev=1.0)
myrand2 = tf.random_normal((4,4),mean=1,stddev=1)

In [ ]:
my_ops = [myrand1,myrand2]

In [ ]:
for op in my_ops:
   print(sess.run(op))
   print("\n")

[[ 0.36502263  0.7655812  -0.66846734  1.8302705 ]
 [-0.26348966 -0.17596287  0.19409649 -1.227079  ]
 [-1.1166319   0.653436    0.83422124 -0.2971182 ]
 [-0.58957106  1.3679285  -0.46110007 -0.28420168]]


[[ 0.47186583  0.8055643   0.6535487   0.63624567]
 [-0.39152193  2.0466785  -0.67753756  1.4030671 ]
 [ 2.182517    0.51116055  2.3268948   1.212547  ]
 [ 2.133995    0.06568801  1.3940461   0.69890773]]




GRAPHS

In [ ]:
graph_one = tf.get_default_graph()
print(graph_one)

In [ ]:
graph_two = tf.Graph()

In [ ]:
print(graph_two is tf.get_default_graph())

False


In [ ]:
with graph_two.as_default():
  print(graph_two is tf.get_default_graph())

True


VARIABLES AND PLACEHOLDERS

In [ ]:
import tensorflow as tf

In [ ]:
sess = tf.InteractiveSession()

/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [ ]:
my_tensor = tf.random_uniform((4,4),1,5)

In [ ]:
my_tensor

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [ ]:
my_var = tf.Variable(my_tensor)

In [ ]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [ ]:
init = tf.global_variables_initializer()
sess.run(init)

In [ ]:
sess.run(my_var)

array([[2.7081318, 2.4926   , 4.0793037, 4.6238894],
       [4.820035 , 3.294907 , 1.4079113, 3.0773845],
       [4.013759 , 2.9210668, 3.4600391, 4.8745213],
       [4.3792133, 2.851705 , 3.2291007, 1.7186785]], dtype=float32)

In [ ]:
ph = tf.placeholder(tf.float32, shape=(None,5))